=== Simulating Mouse Actions

The `Mouse` utility class contains all kinds of methods which allow you to use
or at least simulate the use (depending on the `WebDriver` implementation) of
mouse actions. These are the currently implemented mouse actions:

* `click(PageFragment)`
* `doubleClick(PageFragment)`
* `contextClick(PageFragment)`
* `moveTo(PageFragment)`
* `moveToEach(PageFragment, PageFragment...)`
* `moveToEach(Collection<PageFragment>)`

[source, java]
----
// clicks a button
Mouse.click(button);

// double clicks an image
Mouse.doubleClick(image);

// moves the mouse to the link
Mouse.moveTo(link);

// moves the mouse to each link as they appear
Mouse.moveToEach(fileMenu, fileMenuNew, fileMenuNewPage);
----

==== Mouse.click()

Executes a click on the given `PageFragment` by first moving the mouse to the
center of it.

==== Mouse.doubleClick()

Executes a double click on the given `PageFragment` by first moving the mouse to
the center of it.

==== Mouse.contextClick()

Executes a context click on the given `PageFragment` by first moving the mouse
to the center of it.

==== Mouse.moveToEach()

Moves the mouse to each of the given `PageFragment`s in turn. The page fragments
have to be visible in order to move the mouse to it. This method can be used to
navigate dynamically displayed menu structures because it waits for each page
fragment to be displayed before moving the mouse to it.

==== Mouse.moveTo()

Moves the mouse to the given `PageFragment`. The page fragment has to be visible
in order to move the mouse to it.

==== Fluent API for Mouse Actions

In addition to these single actions the `Mouse` utility class provides
several methods for execution a number of actions with a fluent syntax:

* `on(PageFragment)`
* `sequence()`

[source, java]
----
// actions on fragment
Mouse.on(button).click();
Mouse.on(button).doubleClick();
Mouse.on(button).contextClick();

// sequence
Mouse.sequence().moveTo(image).click();
Mouse.sequence().moveTo(image).moveTo(otherImage).click();
Mouse.sequence().click(image).doubleClick(otherImage);
----
