hub:
  image: selenium/hub:3.4.0
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:2.53.1-beryllium
  links:
    - hub
additionalFirefox:
  image: selenium/node-firefox:2.53.1-beryllium
  links:
    - hub
chrome:
  image: selenium/node-chrome:3.4.0
  links:
    - hub
additionalChrome:
  image: selenium/node-chrome:3.4.0
  links:
    - hub
